tasks:
  - name: "Run Petclinic Backend"
    command: |
      ./mvnw spring-boot:run -pl backend
  - name: "Frontend"
    init: |
      cd frontend
      npm install
      npm run build
      cp build/index.html build/index-orig.html
    command: |
      gp await-port 9977
      export BACKEND_HOST=`gp url 9977`
      cd $GITPOD_REPO_ROOT/frontend
      node patch-index-html.js
      ./node_modules/.bin/serve -s build
ports:
  - port: 9977
    onOpen: open-browser
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true

